### ISSUE TITLE
Some feedback on the current implementation

### ISSUE THREAD

**Issue by HNorlen-zz** [theiliad/IBM-IoTP-ConveyorBelt#5]
Feedback:
- If I max out the rpm the app seems to get locked at max speed. I have to stop and restart before I can lower the rpm.
- If I shake my iPhone I get an "Undo Typing" message, and ay is not updated. 
- To send updated ay data I need to change the rpm of the belt (shaking doesn't trigger a new message).

Suggestions:
- Can we have the app send numerical values as numbers instead of strings? Sending numericals as strings complicates schema/rules creation.
- Can we add a text next to the org link: "Click to open the Watson IoT Platform dashboard."

**Comment by theiliad** [comment]
Thanks Hassi, item 1 is fixed by #4 thanks to @hrhrprasath

**Comment by HNorlen-zz** [comment]
Some more thoughts:
- The little spinning axle keeps on spinning even when I stop the belt.
- No matter what speed the belt is running at, that spinning axle spins at the same rate.
